{
	"version": 1587502282,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/startbutton-sheet0.png",
		"images/buttonsborder-sheet0.png",
		"images/instructions-sheet0.png",
		"images/completescreen-sheet0.png",
		"images/completebutton-sheet0.png",
		"images/highlight-sheet0.png",
		"images/heading-sheet0.png",
		"images/emptytextbox-sheet0.png",
		"images/box_asset-sheet0.png",
		"images/bulletpoint-sheet0.png",
		"images/bulletpoint-sheet1.png",
		"media/completing an activity.m4a",
		"media/completing an activity.ogg",
		"media/correct.m4a",
		"media/correct.ogg",
		"media/error.m4a",
		"media/error.ogg",
		"media/menu buttons.m4a",
		"media/menu buttons.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"ideadata.json",
		"ai-track.min.js",
		"trans.css",
		"ideaLogo.png",
		""
	]
}