{
	"version": 1584706057,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/background-sheet0.png",
		"images/header-sheet0.png",
		"images/middle_circle-sheet0.png",
		"images/orange_select-sheet0.png",
		"images/bdb-sheet0.png",
		"images/descriptionboard-sheet0.png",
		"images/complete-sheet0.png",
		"images/complete-sheet1.png",
		"images/endsheetsheetsheet-sheet0.png",
		"images/sprite-sheet0.png",
		"images/closetrigger-sheet0.png",
		"images/correcttick_asset-sheet0.png",
		"images/bigblue-sheet0.png",
		"images/bigblue-sheet1.png",
		"images/board-sheet0.png",
		"images/cross-sheet0.png",
		"images/cross-sheet1.png",
		"media/completing an activity.m4a",
		"media/completing an activity.ogg",
		"media/menu buttons.m4a",
		"media/menu buttons.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"ideadata.json"
	]
}