{
	"version": 1587506896,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/cmsbg-sheet0.png",
		"images/bgoverlay-sheet0.png",
		"images/heading-sheet0.png",
		"images/startbutton-sheet0.png",
		"images/instruction1-sheet0.png",
		"images/trigger1-sheet0.png",
		"images/line-sheet0.png",
		"images/dotsmall7-sheet0.png",
		"images/dotlarge1-sheet0.png",
		"images/70correctpopup-sheet0.png",
		"images/50correctpopup-sheet0.png",
		"images/incorrectpopup-sheet0.png",
		"images/incorrectpopupclose-sheet0.png",
		"images/100correctpopup-sheet0.png",
		"images/correctpopup-sheet0.png",
		"images/correctpopupclose-sheet0.png",
		"images/checkbutton-sheet0.png",
		"images/tick-sheet0.png",
		"images/cross-sheet0.png",
		"images/instruction2-sheet0.png",
		"images/answerbox-sheet0.png",
		"images/completebutton-sheet0.png",
		"images/completescreen-sheet0.png",
		"images/termtrigger-sheet0.png",
		"images/termbackground-sheet0.png",
		"images/whitebackground-sheet0.png",
		"images/updatedglassesasset4-sheet0.png",
		"images/updatedglassesasset5-sheet0.png",
		"images/inbetween_asset-sheet0.png",
		"images/startscreen_asset-sheet0.png",
		"images/preview_-sheet0.png",
		"images/preview_-sheet1.png",
		"images/preview_-sheet2.png",
		"images/preview_-sheet3.png",
		"images/preview_-sheet4.png",
		"media/completing an activity.m4a",
		"media/completing an activity.ogg",
		"media/correct.m4a",
		"media/correct.ogg",
		"media/error.m4a",
		"media/error.ogg",
		"media/menu buttons.m4a",
		"media/menu buttons.ogg",
		"media/swoosh.m4a",
		"media/swoosh.ogg",
		"media/woop.m4a",
		"media/woop.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"ideadata.json",
		"ai-track.min.js",
		"trans.css",
		"ideaLogo.png",
		""
	]
}